In [1]:
#Sentence embedding using sentence-transformers

from sentence_transformers import SentenceTransformer

In [2]:
model = SentenceTransformer('all-MiniLM-L6-v1')

In [3]:
sentences = [
    "The sun rises in the east.",
    "She likes to drink coffee in the morning.",
    "The library is closed today.",
    "He is learning how to play chess.",
    "A smartphone can be used for many tasks.",
    "The train arrives at the station at 5 PM.",
    "This restaurant serves Italian cuisine.",
    "The garden is full of blooming flowers.",
    "They went hiking in the mountains.",
    "Dogs are loyal and friendly animals."
]


In [4]:
sentences[1]

'She likes to drink coffee in the morning.'

In [5]:
model.encode(sentences[1]).shape

C:\Users\USER\miniconda3\envs\genai\lib\site-packages\transformers\models\bert\modeling_bert.py:440: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(


(384,)

In [6]:
model.encode(sentences[1])

array([-2.99095605e-02,  8.41932744e-02,  7.67828301e-02,  1.16709635e-01,
        1.45563064e-02,  5.48812523e-02,  8.67540091e-02,  2.13659741e-02,
        4.34669293e-02, -8.26784782e-03, -7.68265203e-02, -8.85108113e-02,
       -6.03900738e-02,  1.49077391e-02,  1.41177969e-02,  9.01747961e-03,
        1.06593505e-01, -4.33018357e-02,  7.16544092e-02,  2.53117029e-02,
        4.90440475e-03, -5.74979819e-02,  1.49467126e-01,  8.54823887e-02,
        4.62870635e-02,  2.96713989e-02,  7.67933950e-02, -4.97615561e-02,
       -1.90670714e-02, -1.26746502e-02, -5.99069595e-02,  3.70195098e-02,
       -2.74604075e-02, -4.89989482e-03, -2.23603398e-02,  3.12405434e-02,
        8.97318572e-02,  5.24966717e-02, -1.28071662e-02,  1.07276507e-01,
       -3.82454582e-02, -8.32148492e-02,  3.27273607e-02, -1.26611814e-02,
       -1.31124854e-01, -6.49928302e-03,  4.71679047e-02, -1.79691128e-02,
        8.42707157e-02,  8.44834000e-03, -7.93756396e-02, -9.10261944e-02,
       -6.70957491e-02, -

In [7]:
#Sentence embedding using Langchain

from langchain.embeddings import HuggingFaceEmbeddings

In [8]:
embedding_model = "sentence-transformers/all-MiniLM-L6-v1"

In [9]:
model_kwargs = {"device": "cpu"}

embeddings = HuggingFaceEmbeddings(model_name = embedding_model, model_kwargs = model_kwargs)

C:\Users\USER\AppData\Local\Temp\ipykernel_30176\4058773246.py:3: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name = embedding_model, model_kwargs = model_kwargs)


In [10]:
embedding_vector = embeddings.embed_query(sentences[1])

In [11]:
len(embedding_vector)

384

In [12]:
#Sentence embedding using Transformers - Huggingface

import torch
from transformers import BertTokenizer, BertModel
import random

In [13]:
from sklearn.metrics.pairwise import cosine_similarity
random_seed=42
random.seed(random_seed)
torch.manual_seed(random_seed)

In [14]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")
model=BertModel.from_pretrained("bert-base-uncased")

In [16]:
encode_val=tokenizer.batch_encode_plus([sentences[1]],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [17]:
encode_val

{'input_ids': tensor([[ 101, 2016, 7777, 2000, 4392, 4157, 1999, 1996, 2851, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [19]:
input_ids = encode_val['input_ids']
attention_mask = encode_val['attention_mask']
input_ids

tensor([[ 101, 2016, 7777, 2000, 4392, 4157, 1999, 1996, 2851, 1012,  102]])

In [20]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [21]:
word_embeddings

tensor([[[ 0.1900, -0.1599, -0.2854,  ..., -0.1887,  0.7630,  0.5221],
         [ 0.6969, -0.6491, -0.2434,  ..., -0.4393,  0.9461,  0.1149],
         [ 0.6999,  0.1731,  0.4656,  ..., -0.1875,  0.3450,  0.0663],
         ...,
         [ 0.2275,  0.5197,  0.1349,  ..., -1.0104,  0.2131, -1.0064],
         [ 0.3403, -0.5184, -0.3848,  ..., -0.0019,  0.9498, -0.4972],
         [ 0.7428,  0.0048,  0.1801,  ...,  0.1981,  0.0301, -0.5262]]])

In [22]:
word_embeddings.shape

torch.Size([1, 11, 768])

In [23]:
decode_val = tokenizer.decode(input_ids[0], skip_special_tokens=True)
decode_val

'she likes to drink coffee in the morning.'